name: tag_game_unit_test_and_build
on:
  pull_request:
    branches:
      - main
jobs:
  gtest:
    name: Run tests with google test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: echo enviroment.
        run: |
          pwd 
          ls 
          cmake --version
          make --version
      - name: Run Tests
        run: |
          make test
      - name: Clean up build Dir.
        run : |
          make clean
  buildup:
    name: Build up with cmake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Run Build
        run: |
          make buildup
